### ISSUE TITLE
nacos客户端连接需要用户密码

### ISSUE THREAD

**Issue by mayou33** [shiyindaxiaojie/Sentinel#5]
因为nacos客户端连接需要用户密码。

  Nacos 存储规则，如果您设置了 sentinel.metrics.type=nacos，需要调整相关配置
sentinel.rule.nacos.server-addr=localhost:8848
sentinel.rule.nacos.namespace=demo
sentinel.rule.nacos.group-id=sentinel

请问一下，这个支持写nacos的用户密码吗

**Comment by shiyindaxiaojie** [comment]
fixed
